### ISSUE TITLE
Issue on the output of marketing_campaign.ipynb

### ISSUE THREAD

**Issue by suresh-abeyweera** [IBMDecisionOptimization/docplex-examples#27]
'data' shows all the 2 confidence scores for each customers.If we thoroughly investigate we can notice no customers has higher probability of selecting for Car Loans.But if we analyze the model output we can see some of the Customers are offered CAR Loan,,Practically can this be done? And if we go through the objective function 
"mdl.sum( channelVars[idx,p,idx2] * c.factor * productValue[p]* o.Confidence1  
            for p in productsR 
            for idx,o in offers[offers['Product1'] == products[p]].iterrows()  
            for idx2, c in channels.iterrows())"

that each decission variable should be multiplied each confidance score,How this can be applied since for Car Loans no probability is given..

**Comment by vlkong** [comment]
Hi,

I think the person who initially wrote this example overlook the data at hands, and forgot to factor in
the confidence for Car Loans (probably because he saw that there was no Car Loan in `data` !)

This is clearly a bug in the model.

Thanks for the report, I will follow up with dev team to have this fixed.
