### ISSUE TITLE
CpoException: Executable file should be given in 'execfile' context attribute.

### ISSUE THREAD

**Issue by Khaledjallouli** [IBMDecisionOptimization/docplex-examples#38]
Hello,

I wanted to run one of the examples on my laptop but I got an error in the following cell:

```
# Solve the model
print("\nSolving model....")
msol = mdl.solve(TimeLimit=20)
```

The error is: 
CpoException: Executable file should be given in 'execfile' context attribute.

Did anyone else had the same problem, please?

Thank you for your help.

**Comment by vlkong** [comment]
Hello,
In order to solve constraint programming models, docplex needs the `cpoptimizer` executable (`cpoptimizer.exe` on Windows)  to be in your PATH.
This executable is in your <COS_INSTALLATION_DIR>/cpoptimizer/bin/x64_win64 directory if you are on windows (replace x64_win64 with your platform).
Best regards,

**Comment by Khaledjallouli** [comment]
Thank you for the hint. Solved by  `pip install cplex`
