### ISSUE TITLE
Docplex MP: How to translate logical implication

### ISSUE THREAD

**Issue by Julia000199** [IBMDecisionOptimization/docplex-examples#52]
Hi everybody!
Currently I am writing cplex to python docplex conversion model and I have cplex side binding as follows:
       
 forall (i in point: i == 0, j in point: j != 0, k in truck)
             x[0][j][k] == 1 && f[j][k] >= 0 => sl[j][k] - sl[0][k] + f[j][k] > = 0;

I want to convert this binding to docplex, however I don't know how to write it. Can you help me?
Thanks.

**Comment by PhilippeCouronne** [comment]
Hello,
  You're not mentioning the original format of the model you want to convert to docplex, seems like OPL?

To explain how to map the constraint syntax you posted to Docplex, let me proceed in steps:

- First, the format of constraint is of the form <logical_condition> => <linear_constraint>, in other terms, when some logical condition is true (i.e. equal to 1), the constraint has to be satisfied (otherwise, it is free, maybe satisfied, maybe not, we don't know). 
What's more in your case, the logical condition is built using constraints, so the general pattern here is:

if [ C1 and C2 are satisfied]  then C3 must be satisfied.

This can be mapped to docplex easily. The essential point here is that DOcplex provides a binary variable mirroring the "truth value" of a constraint, that is, equal to 1 if and only if the constraint is satisfied. Of course the constraints should *not* be added to the model, otherwise they would always be satisfied. 
Let me illustrate with a small simple code:
```

from docplex.mp.model import Model
m = Model()
x = m.integer_var()
y = m.integer_var()
z = m.integer_var(lb=1, ub=10)
ctx3 = (x == 3)
cty5 = (y == 5)
ctz7 = (z == 7)
m.add(x == 3)
m.add(y == 5)
m.add((ctx3 & cty5) <= ctz7)
m.minimize(x + y)
s1 = m.solve()
s1.display()
```

Here I create two constraints `ctx3` and `cty5`; note they are NOT added to the model, so we don't know in advance what their status will be .

The syntax:

m.add((ctx3 & cty5) <= ctz7)

illustrates several points:

- a constraint can be used as an expression, it is converted into its binary status variable
- the '&' operator computes the logical AND of the two status variables
- this binary logical is in turn usable as a binary variable, equal to 1 when both statuses are 1
Then we state that the And is less than the status of the target constraint (y==7),
which means when the And is true, the status of (y==7) becomes true, hence y==7

Applied to your (simplified) case , this would look like:

m.add( ( (X == 1) & (F >= 0)) <= (S2 -S1 + F >=0))

**Comment by Julia000199** [comment]
Hi,
I understand what you mean, thank you very much for your support.
Best regards
